name = "Sainsc"
uuid = "4c4340ea-7f9e-46b4-8512-61f1f6c41a11"
authors = ["Niklas Müller-Bötticher <niklasmueboe@github.com>"]
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Unzip = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"

[weakdeps]
AutomaticSingleCellToolbox = "e6202555-39b2-4a04-a024-3007b9347e88"
CellScopes = "708d50d9-0a30-4b01-8594-5d83c0e43023"
Muon = "446846d7-b4ce-489d-bf74-72da18fe3629"
SingleCellProjections = "03d38035-ed2f-4a36-82eb-797f1727ab2e"

[extensions]
AnnDataExt = "Muon"
AutomaticSingleCellToolboxExt = "AutomaticSingleCellToolbox"
CellScopesExt = "CellScopes"
SingleCellProjectionsExt = "SingleCellProjections"

[compat]
AutomaticSingleCellToolbox = "0.9"
BlockArrays = "0.16,1"
CSV = "0.10"
CategoricalArrays = "0.9,0.10"
CellScopes = "1"
DataFrames = "1"
ImageFiltering = "0.7"
LinearAlgebra = "1"
Muon = "0.2"
OffsetArrays = "1.11"
PooledArrays = "1"
SingleCellProjections = "0.3, 0.4"
SparseArrays = "1"
Unzip = "0.2"
julia = "1.9"
